"""unique url per user

Revision ID: 3ba8f78636d2
Revises: bfdf5c1aa6a7
Create Date: 2026-03-10 23:59:16.196957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ba8f78636d2'
down_revision: Union[str, Sequence[str], None] = 'bfdf5c1aa6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('fts_vector_idx'), table_name='embeddings', postgresql_using='gin')
    op.drop_index(op.f('ix_embeddings_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_website_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('websites_api_key'), table_name='websites')
    op.drop_table('websites')
    op.drop_table('users')
    op.drop_index(op.f('chat_histories_website_id'), table_name='chat_histories')
    op.drop_table('chat_histories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_histories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('website_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint("role::text = ANY (ARRAY['user'::character varying, 'assistant'::character varying]::text[])", name=op.f('check_chat_role_valid')),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_chat_histories_website_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_histories_pkey'))
    )
    op.create_index(op.f('chat_histories_website_id'), 'chat_histories', ['website_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=45), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(length=200), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('websites',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('websites_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=200), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('api_key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='websites_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='websites_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('websites_api_key'), 'websites', ['api_key'], unique=True)
    op.create_table('embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chunk', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chunk_metadata', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('website_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fts_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_embeddings_website_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('embeddings_pkey'))
    )
    op.create_index(op.f('ix_embeddings_website_id'), 'embeddings', ['website_id'], unique=False)
    op.create_index(op.f('ix_embeddings_id'), 'embeddings', ['id'], unique=False)
    op.create_index(op.f('fts_vector_idx'), 'embeddings', ['fts_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
